defaults: ../../grpo_math_1B_megatron.yaml
grpo:
  max_num_steps: 100
  num_prompts_per_step: 2
checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-Math-1.5b-instruct-1n8g-megatron-yarn-8k
  save_period: 20
policy:
  model_name: Qwen/Qwen2.5-Math-1.5B-Instruct
  train_global_batch_size: 32
  train_micro_batch_size: 1
  max_total_sequence_length: 8192
  make_sequence_length_divisible_by: 64
  megatron_cfg:
    force_reconvert_from_hf: true
  hf_config_overrides:
    rope_scaling:
      rope_type: yarn
      rope_theta: 10000
      factor: ${div:${policy.max_total_sequence_length},${policy.hf_config_overrides.rope_scaling.original_max_position_embeddings}}
      original_max_position_embeddings: 4096
      truncate: true
      beta_fast: 32
      beta_slow: 1
      mscale: 1
      mscale_all_dim: 0
logger:
  wandb:
    project: yarn
    name: grpo-qwen2.5-Math-1.5b-instruct-1n8g-megatron-yarn-8k
cluster:
  gpus_per_node: 8
